# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '4.6.1', '6.0.x', '8.0.x', '9.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build-win-x64
      run: dotnet build --no-restore -r win-x64 -v diagnostic
    - name: Build-win-x86
      run: dotnet build --no-restore -r win-x86 -v diagnostic
    - name: Build-linux-x86
      run: dotnet build --no-restore -r linux-x64 -v diagnostic
    - name: Build-osx-x86
      run: dotnet build --no-restore -r osx-x64 -v diagnostic
