# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build-Win-x64
      run: dotnet build MrAdvice.Weaver\\MrAdvice.Weaver.csproj --no-restore -r win-x64 -v diagnostic
    - name: Build-Win-x86
      run: dotnet build MrAdvice.Weaver\\MrAdvice.Weaver.csproj --no-restore -r win-x86 -v diagnostic
