# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Build-win-x64
      run: dotnet build MrAdvice.Weaver\\MrAdvice.Weaver.csproj -r win-x64 -v diagnostic
    - name: Build-win-x86
      run: dotnet build MrAdvice.Weaver\\MrAdvice.Weaver.csproj -r win-x86 -v diagnostic
    - name: Build-linux-x86
      run: dotnet build MrAdvice.Weaver\\MrAdvice.Weaver.csproj -r linux-x64 -v diagnostic
    - name: Build-osx-x86
      run: dotnet build MrAdvice.Weaver\\MrAdvice.Weaver.csproj -r osx-x64 -v diagnostic
